'use client';
import {useMemo,useState} from 'react';
import {HeartPulse,Mic,ShieldAlert,Stethoscope,Users,Languages,Accessibility,WifiOff,PhoneCall,Copy,CheckCircle2} from 'lucide-react';
import {assessMaternalRisk} from '../lib/risk';import {checkFollowUpTeachback} from '../lib/teachback';import {saveLocal} from '../lib/offline';import {buildEmergencyHandoff} from '../lib/emergencyHandoff';import PwaBoot from '../components/PwaBoot';
type Mode='patient'|'clinician'|'carebridge'|'access';
export default function Home(){
 const[saveError,setSaveError]=useState('');const[mode,setMode]=useState<Mode>('patient');const[symptom,setSymptom]=useState('I have had a severe headache since yesterday and my feet are more swollen.');const[sys,setSys]=useState(151);const[dia,setDia]=useState(96);const[saved,setSaved]=useState(false);const[handoff,setHandoff]=useState<string|null>(null);const[planConfirmed,setPlanConfirmed]=useState(false);const[teachback,setTeachback]=useState('');const[copied,setCopied]=useState(false);
 const risk=useMemo(()=>assessMaternalRisk([{type:'bp',value:sys},{type:'bp_diastolic',value:dia},{type:'symptom',text:symptom}]),[sys,dia,symptom]);
 async function save(){if(!validBp){setSaveError('Enter valid blood-pressure readings before saving.');return;}try{await saveLocal('health-signal',{symptom,bloodPressure:{systolic:sys,diastolic:dia},risk,source:'patient',verification:'unverified'});setSaved(true);setSaveError('')}catch{setSaved(false);setSaveError('Could not save on this device. Please check browser storage settings.')}}
 function makeHandoff(){const h=buildEmergencyHandoff({pregnancyWeeks:31,symptoms:[symptom],bp:`${sys}/${dia} mmHg`});setHandoff(JSON.stringify(h,null,2))}
 async function copyHandoff(){if(!handoff)return;await navigator.clipboard?.writeText(handoff);setCopied(true)}
 const validBp=Number.isFinite(sys)&&Number.isFinite(dia)&&sys>=40&&sys<=300&&dia>=20&&dia<=200&&sys>dia;const teachbackResult=checkFollowUpTeachback(teachback,planConfirmed);const teachbackOk=teachbackResult.status==='match';
 return <main className="wrap"><a className="skip" href="#content">Skip to health content</a><div className="topline"><PwaBoot/><span className="badge">ForgeHacks 2026 · AI + Healthcare</span></div><div className="hero"><div><h1 className="big">AURA <span>Health AI</span></h1><p className="lead">Health changes should not disappear between visits.</p><p className="muted">Offline-first early warning and care continuity. AURA supports decisions; clinicians remain the clinical authority.</p></div><div className="principle"><b>Notice early.</b><b>Explain simply.</b><b>Escalate safely.</b></div></div>
 <div className="nav" role="navigation" aria-label="AURA modes">{([['patient','My health'],['clinician','Clinician'],['carebridge','CareBridge'],['access','Access']] as const).map(([k,l])=><button key={k} aria-current={mode===k?'page':undefined} className={mode===k?'active':''} onClick={()=>setMode(k)}>{l}</button>)}</div>
 <div id="content">
 {mode==='patient'&&<div className="grid"><section className="card span8"><div className="eyebrow">AURA GUARDIAN</div><div className="row"><Mic/><h2>What changed today?</h2></div><p className="muted">Type what changed. Patient-entered information stays marked as unverified until confirmed or reviewed.</p><textarea aria-label="Describe what changed" className="input" rows={4} value={symptom} onChange={e=>{setSymptom(e.target.value);setSaved(false)}}/><div className="metric"><label>Blood pressure</label><div><input aria-label="Systolic blood pressure" className="bp" type="number" min="40" max="300" value={sys} onChange={e=>{setSys(Number(e.target.value));setSaved(false);setHandoff(null)}}/><span>/</span><input aria-label="Diastolic blood pressure" className="bp" type="number" min="20" max="200" value={dia} onChange={e=>{setDia(Number(e.target.value));setSaved(false);setHandoff(null)}}/><span>mmHg</span></div></div>{!validBp&&<p role="alert">Enter a valid blood-pressure reading (systolic must exceed diastolic).</p>}<div role="status" aria-live="polite" className={'result '+risk.level}><span>{risk.level==='urgent'?'Needs prompt review':risk.level==='watch'?'Watch change':'Routine'}</span><strong>{risk.level.toUpperCase()}</strong>{risk.reasons.map((r,i)=><p key={i}>{r}</p>)}</div><div className="row"><button className="btn primary" disabled={!validBp} onClick={save}>{saved?'Saved on this device ✓':'Save securely on this device'}</button>{saveError&&<p role="alert">{saveError}</p>}<button className="btn secondary" onClick={()=>{if('speechSynthesis'in window)speechSynthesis.speak(new SpeechSynthesisUtterance(risk.reasons.join(' ')))}}>Read aloud</button></div></section>
 <aside className={'card span4 '+(risk.level==='urgent'?'emergency':'')}><ShieldAlert size={30}/><div className="eyebrow">SAFETY PATH</div><h2>{risk.level==='urgent'?'Get prompt medical help':'Guardian is watching'}</h2><p>{risk.level==='urgent'?'A configured warning pattern was detected. AURA is not diagnosing the cause.':'No urgent demo rule triggered.'}</p>{risk.level==='urgent'&&<><button className="btn danger" disabled={!validBp} onClick={makeHandoff}><PhoneCall size={18}/> Prepare emergency handoff</button><div className="offline-note"><WifiOff size={18}/>Warning + saved handoff work offline after the app is cached.</div></>}</aside>
 {handoff&&<section className="card span12" aria-live="polite"><div className="row"><ShieldAlert/><h2>Emergency Handoff Card</h2></div><p className="muted">Patient-entered information — clinician verification required. AURA has not transmitted this anywhere.</p><pre className="handoff">{handoff}</pre><button className="btn secondary" onClick={copyHandoff}>{copied?<CheckCircle2 size={18}/>:<Copy size={18}/>} {copied?'Copied':'Copy for emergency team'}</button></section>}
 <section className="card span6"><div className="eyebrow">YOUR BASELINE</div><h3>Changes, not isolated numbers</h3><div className="timeline"><div className="item"><span className="dot"/>126/82 <small>demo baseline</small></div><div className="item"><span className="dot"/>137/89 <small>demo trend</small></div><div className="item current"><span className="dot"/>{sys}/{dia} <small>today</small></div></div></section><section className="card span6"><div className="eyebrow">MATERNAL GUARDIAN</div><h3>Pregnancy → postpartum</h3><p className="muted">Connects symptoms, measurements, appointments and clinician-approved instructions. Demo rules are not a clinically validated protocol.</p></section></div>}
 {mode==='clinician'&&<div className="grid"><section className="card span8"><div className="eyebrow">COMMAND CENTER · SYNTHETIC DEMO</div><div className="row"><Stethoscope/><h2>Who changed — and why?</h2></div>{[['urgent','Thandi M.','31 weeks · BP trend + severe headache'],['watch','Amara K.','New dizziness after medication change'],['routine','Sarah N.','Care plan completed']].map(([s,n,d])=><div className="patient-row" key={n}><span className={'status '+s}/><span><b>{n}</b><small>{d}</small></span><strong>{s}</strong></div>)}</section><aside className="card span4"><h3>Provenance first</h3><p className="muted">Clinicians should see whether each fact came from the patient, device, lab or clinical record and whether it has been verified.</p></aside></div>}
 {mode==='carebridge'&&<div className="grid"><section className="card span6"><Users/><div className="eyebrow">DOCTOR → PATIENT</div><h2>Confirm the care plan</h2><div className="signal"><b>Demo follow-up</b><small>2 weeks</small></div><button className="btn primary" onClick={()=>setPlanConfirmed(true)}>{planConfirmed?'Plan confirmed ✓':'Confirm demo plan'}</button></section><section className="card span6"><HeartPulse/><div className="eyebrow">PATIENT → DOCTOR</div><h2>Teach it back</h2><p className="muted">Explain when the follow-up is due. AURA checks this against the confirmed demo plan and asks for clarification when it does not match.</p><textarea className="input" aria-label="Teach back the care plan" rows={3} value={teachback} onChange={e=>setTeachback(e.target.value)}/><div role="status" className={'result '+(teachbackOk?'routine':'watch')}>{teachbackResult.message}</div></section></div>}
 {mode==='access'&&<div className="grid"><section className="card span6"><Languages/><h2>Speak the way you speak</h2><p className="muted">Architecture supports language packs and code-switch-aware speech. The current prototype does not claim universal language coverage.</p><div className="chips"><span>English</span><span>isiZulu target</span><span>French target</span></div></section><section className="card span6"><Accessibility/><h2>Built for more people</h2><p className="muted">Large touch targets, keyboard access, screen-reader live status, high contrast, voice + text and an offline safety path.</p></section></div>}
 </div><footer><b>AURA is decision support, not a diagnosis.</b> It does not prescribe, change medication or replace qualified clinicians or emergency services.</footer></main>
}